### ISSUE TITLE
hi. can you help me

### ISSUE THREAD

**Issue by kobrin666** [osorionicolas/visa-bot#1]
I want to get the date for myself. But I don't understand how to run your program. Can you write instructions on how it works? Here is my link https://service2.diplo.de/rktermin/extern/appointment_showMonth.do?locationCode=mins&realmId=231&categoryId=373 Thanks

**Comment by osorionicolas** [comment]
Hi! sorry I was doing some changes lately, I have alredy reverted them. Also, I added a README. I don't know if there were changes on the pages but use this as a base. (Maybe it still works). Just let me know if you have any other question

**Comment by kobrin666** [comment]
I downloaded and unzipped the archive. changed the link for your city. the bot is launched through the command line? I made some changes, but I still can't run it. can you explain with your fingers?

**Comment by osorionicolas** [comment]
Have you ever worked with docker? That's how you run the application. If you are using Windows you can install Docker Desktop and it will give you the needed tools. Then just run "docker-compose up -d" in the folder you want (germany in this case)

**Comment by kobrin666** [comment]
I have windows 7 ultimate. I can't install docker desktop, only docker toolbox(((

**Comment by osorionicolas** [comment]
well you can install the dependencies following the Dockerfile (previous installing node) and run the app manually

RUN is to execute commands on cmd
WORKDIR is the folder when you are working
COPY is to put the index file in the folder
CMD is the command to run the app
